name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.201' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet ERACompiler/restore
    - name: Build
      run: dotnet ERACompiler/build --configuration Release --no-restore
    - name: Test
      run: dotnet ERACompiler/test --no-restore --verbosity normal
